# Generated by Django 5.0.4 on 2024-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_made_first_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('unternehmensleiter', 'Unternehmensleiter'), ('mitarbeiter', 'Mitarbeiter')], max_length=40, null=True, verbose_name='Benutzerrolle'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
