# Generated by Django 5.0.4 on 2024-05-01 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_made_first_test_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_list',
            field=models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter der Organisation'),
        ),
    ]
