# Generated by Django 5.0.4 on 2024-06-07 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0004_add_status_and_notes_to_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracceptancetestresult',
            name='test_procedure_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_tests.testprocedureresult', verbose_name='Testprozedurresultat'),
        ),
    ]
