# Generated by Django 5.0.4 on 2024-04-24 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_made_first_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='TestProcedureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('test_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.testprocedure', verbose_name='Testprozedur')),
            ],
        ),
        migrations.CreateModel(
            name='UserAcceptanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Beschreibung')),
                ('pre_conditions', models.TextField(blank=True, help_text='Bedingungen vor dem Test', max_length=500, null=True, verbose_name='Vorbedingungen')),
                ('steps', models.TextField(blank=True, help_text='Schritte für den Test', max_length=500, null=True, verbose_name='Schritte')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('expected_result', models.TextField(blank=True, help_text='Resultat dass nach dem Test erwartet wird', max_length=500, null=True, verbose_name='Erwartetes Resultat')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.project', verbose_name='Projekt')),
            ],
        ),
        migrations.AddField(
            model_name='testprocedure',
            name='acceptance_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.useracceptancetest', verbose_name='Akzeptanztest'),
        ),
        migrations.CreateModel(
            name='UserAcceptanceTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('acceptance_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.useracceptancetest', verbose_name='Akzeptanztest')),
                ('test_procedure_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.testprocedureresult', verbose_name='Testprozedurresultat')),
            ],
        ),
    ]
